### ISSUE TITLE
Doesn't de-install properly

### ISSUE THREAD

**Issue by ThomasDaheim** [Piwigo/PWG_Stuffs#4]
Hi,

I have installed the plugin and played around with it a bit. Since I decided not to use it I have de-activated and deleted it. Unfortunately, it hasn't de-installed itself completely! The "blocks" of albums still remains behind - previously all albums where shown in one line next to each other.

![clipboard02](https://cloud.githubusercontent.com/assets/14020617/10716754/a3c9c83e-7b42-11e5-9216-3a4d58197f6c.jpg)

**Comment by mistic100** [comment]
Hi

I don't think this has nothing to do with the plugin.

And also I don't see anything abnormal in your screenshot, this is the standard display of albums (chek the demo on piwigo.org website).

Give the link of your gallery for further help.

**Comment by ThomasDaheim** [comment]
Hi,

link is http://www.feuster.com/piwigo. So probably I had something working previously to change the look & feel? So I only need to find that once again :-)

Thanks,
Thomas

**Comment by mistic100** [comment]
Yep that's the standard display, no problem with the plugin.
